# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImportNMEA
                                 A QGIS plugin
 Lets you read NMEA ASCII files and import points and attributes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-17
        copyright            : (C) 2021 by Francesco Pirotti University of Padova
        email                : francesco.pirotti@unipd.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Francesco Pirotti University of Padova'
__date__ = '2021-07-17'
__copyright__ = '(C) 2021 by Francesco Pirotti University of Padova'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImportNMEA class from file ImportNMEA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .import_nmea import ImportNMEAPlugin
    return ImportNMEAPlugin(iface)
